// Generated by CoffeeScript 1.7.1
var image, imageWidth;

if ($('body').length > 0) {
  image = $('.gallery_content .image');
  imageWidth = image.width();
  image.css("height", imageWidth * 0.5625);
  $(window).on('resize', function() {
    imageWidth = image.width();
    return image.css("height", imageWidth * 0.5625);
  });
}
