// Generated by CoffeeScript 1.7.1
var article, article_height, gallery, viewport;

if ($('body').length > 0) {
  article = $('.text .row');
  gallery = $('.gallery');
  viewport = window.innerHeight;
  article_height = article.height();
  article.css("height", article_height);
  gallery.css("height", viewport);
  $(window).on('resize', function() {
    viewport = window.innerHeight;
    article.css("height", article_height);
    return gallery.css("height", viewport);
  });
}
