// Generated by CoffeeScript 1.7.1
var article, article_height, content, footer, footer_height, gallery, intro, push, viewport;

if ($('body').length > 0) {
  article = $('.text_quote .row');
  gallery = $('.gallery');
  intro = $('#intro');
  footer = $('footer');
  push = $('.push-footer');
  content = $('#content');
  viewport = window.innerHeight;
  article_height = article.height();
  footer_height = footer.height();
  article.css("height", article_height);
  gallery.css("height", viewport / 1.25);
  intro.css("height", viewport);
  footer.css("height", footer_height);
  push.css("height", footer_height);
  content.css("margin-bottom", -footer_height);
  $(window).on('resize', function() {
    viewport = window.innerHeight;
    article_height = article.height();
    footer_height = footer.height();
    article.css("height", article_height);
    gallery.css("height", viewport);
    intro.css("height", viewport);
    footer.css("height", footer_height);
    push.css("height", footer_height);
    return content.css("margin-bottom", -footer_height);
  });
}
