// Generated by CoffeeScript 1.8.0
var menu, trigger;

if ($('#menu_small').length > 0) {
  menu = $('#menu_small_collapsed');
  trigger = $('#hamburger');
  trigger.click(function() {
    return menu.toggleClass("active");
  });
}
